const movies = [
    {
        Title: "Rang",
        Year: "1993",
        Rated: "N/A",
        Released: "09 Jul 1993",
        Runtime: "150 min",
        Genre: "Drama, Romance",
        Director: "Talat Jani",
        Writer: "Rumi Jaffery (screenplay), Talat Jani (story), Sagar Sarhadi (dialogue)",
        Actors: "Jeetendra, Amrita Singh, Kamal Sadanah, Ayesha Jhulka",
        Plot:
            "Although Suchitra has been marry to Madhav Singh for years she has always been conscious about maintaining a slim figure which in her believe will make her look young. She watched helplessly as her only daughter, Indu get married without her consent to Ajay Malhotra while both are proud parents to two daughters, Pooja and Kaajal. Suchitra and Indu manage a business but there methods of exploiting workers are unacceptable to Ajay who decides to leave the house with Pooja. Years later Ajay return and is now elected as the managing director of the business only to invite the wrath of his mother-in-law and estranged wife. While Kaajal have matured and is in love with her fellow collegian, Yogi Joshi - unknown to her that Pooja also have feelings for Yogi - it is this love triangle that will bring the two sisters face to face with their parents changing lives forever.",
        Language: "Hindi",
        Country: "India",
        Awards: "N/A",
        Poster: "https://m.media-amazon.com/images/M/MV5BNzM1NzM4Nzk5OV5BMl5BanBnXkFtZTcwODIyNDE0MQ@@._V1_SX300.jpg",
        Ratings: [{ Source: "Internet Movie Database", Value: "4.7/10" }],
        Metascore: "N/A",
        imdbRating: "4.7",
        imdbVotes: "183",
        imdbID: "tt0193449",
        Type: "movie",
        DVD: "N/A",
        BoxOffice: "N/A",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
    },
    {
        Title: "Bhaag Milkha Bhaag",
        Year: "2013",
        Rated: "Not Rated",
        Released: "12 Jul 2013",
        Runtime: "186 min",
        Genre: "Biography, Drama, Sport",
        Director: "Rakeysh Omprakash Mehra",
        Writer: "Prasoon Joshi",
        Actors: "Farhan Akhtar, Sonam Kapoor, Pawan Malhotra, Art Malik",
        Plot:
            'The true story of the "Flying Sikh" - world champion runner and Olympian Milkha Singh -- who overcame the massacre of his family, civil war during the India-Pakistan partition, and homelessness to become one of India\'s most iconic athletes.',
        Language: "Hindi",
        Country: "India",
        Awards: "52 wins & 34 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTY1Nzg4MjcwN15BMl5BanBnXkFtZTcwOTc1NTk1OQ@@._V1_SX300.jpg",
        Ratings: [
            { Source: "Internet Movie Database", Value: "8.2/10" },
            { Source: "Rotten Tomatoes", Value: "72%" },
        ],
        Metascore: "N/A",
        imdbRating: "8.2",
        imdbVotes: "61,744",
        imdbID: "tt2356180",
        Type: "movie",
        DVD: "21 May 2017",
        BoxOffice: "$1,636,731",
        Production: "N/A",
        Website: "N/A",
        Response: "True",
    },
    {
        Title: "PK",
        Year: "2014",
        Rated: "Not Rated",
        Released: "19 Dec 2014",
        Runtime: "153 min",
        Genre: "Comedy, Drama, Musical, Sci-Fi",
        Director: "Rajkumar Hirani",
        Writer: "Rajkumar Hirani, Abhijat Joshi",
        Actors: "Aamir Khan, Rajinder Sharma Nanu, Anushka Sharma, Sushant Singh Rajput",
        Plot:
            "P. K. is a comedy of ideas about a stranger in the city, who asks questions that no one has asked before. They are innocent, child-like questions, but they bring about catastrophic answers. People who are set in their ways for generations, are forced to reappraise their world when they see it from PK's innocent eyes. In the process PK makes loyal friends and powerful foes. Mends broken lives and angers the establishment. P. K.'s childlike curiosity transforms into a spiritual odyssey for him and millions of others. The film is an ambitious and uniquely original exploration of complex philosophies. It is also a simple and humane tale of love, laughter and letting-go. Finally, it is a moving saga about a friendship between strangers from worlds apart.",
        Language: "Hindi",
        Country: "India",
        Awards: "20 wins & 15 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTYzOTE2NjkxN15BMl5BanBnXkFtZTgwMDgzMTg0MzE@._V1_SX300.jpg",
        Ratings: [
            { Source: "Internet Movie Database", Value: "8.1/10" },
            { Source: "Rotten Tomatoes", Value: "77%" },
        ],
        Metascore: "N/A",
        imdbRating: "8.1",
        imdbVotes: "165,607",
        imdbID: "tt2338151",
        Type: "movie",
        DVD: "26 Mar 2017",
        BoxOffice: "$10,616,104",
        Production: "Vinod Chopra Productions",
        Website: "N/A",
        Response: "True",
    },
    {
        Title: "2001: A Space Odyssey",
        Year: "1968",
        Rated: "G",
        Released: "24 Jun 1970",
        Runtime: "149 min",
        Genre: "Adventure, Sci-Fi",
        Director: "Stanley Kubrick",
        Writer: "Stanley Kubrick (screenplay by), Arthur C. Clarke (screenplay by)",
        Actors: "Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter",
        Plot:
            '"2001" is a story of evolution. Sometime in the distant past, someone or something nudged evolution by placing a monolith on Earth (presumably elsewhere throughout the universe as well). Evolution then enabled humankind to reach the moon\'s surface, where yet another monolith is found, one that signals the monolith placers that humankind has evolved that far. Now a race begins between computers (HAL) and human (Bowman) to reach the monolith placers. The winner will achieve the next step in evolution, whatever that may be.',
        Language: "English, Russian",
        Country: "UK, USA",
        Awards: "Won 1 Oscar. Another 15 wins & 11 nominations.",
        Poster: "https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
        Ratings: [
            { Source: "Internet Movie Database", Value: "8.3/10" },
            { Source: "Rotten Tomatoes", Value: "92%" },
            { Source: "Metacritic", Value: "84/100" },
        ],
        Metascore: "84",
        imdbRating: "8.3",
        imdbVotes: "610,901",
        imdbID: "tt0062622",
        Type: "movie",
        DVD: "06 Feb 2014",
        BoxOffice: "$60,405,931",
        Production: "Metro Goldwyn Mayer",
        Website: "N/A",
        Response: "True",
    },
];
export default movies;
